//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartMarket.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartMarket.BLL.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All your settings is saved..
        /// </summary>
        public static string AllSettingSaved {
            get {
                return ResourceManager.GetString("AllSettingSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach  card.
        /// </summary>
        public static string AttachCard {
            get {
                return ResourceManager.GetString("AttachCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YOU&apos;RE IS AUTHINFICATED..
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance was created..
        /// </summary>
        public static string BalanceCreated {
            get {
                return ResourceManager.GetString("BalanceCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create balance.
        /// </summary>
        public static string CreateBalance {
            get {
                return ResourceManager.GetString("CreateBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email was confirmed..
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation. SMART MARKET..
        /// </summary>
        public static string EmailConfirmHeader {
            get {
                return ResourceManager.GetString("EmailConfirmHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not confirmed.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your account by.
        /// </summary>
        public static string EmailText {
            get {
                return ResourceManager.GetString("EmailText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to link.
        /// </summary>
        public static string LinkName {
            get {
                return ResourceManager.GetString("LinkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to a platform where you can find a variety of tests in programming languages and IT disciplines..
        /// </summary>
        public static string NureDescription {
            get {
                return ResourceManager.GetString("NureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And if you feel that you need to deepen your knowledge,       our useful books and lectures are at your service!.
        /// </summary>
        public static string NureEnding {
            get {
                return ResourceManager.GetString("NureEnding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kharkiv National University of Radioelectronics.
        /// </summary>
        public static string NureHeader {
            get {
                return ResourceManager.GetString("NureHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLEASE AUTHORIZE TO GETTING ACCESS.
        /// </summary>
        public static string PleaseAuthorize {
            get {
                return ResourceManager.GetString("PleaseAuthorize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take tests in:.
        /// </summary>
        public static string TechnologiesTittle {
            get {
                return ResourceManager.GetString("TechnologiesTittle", resourceCulture);
            }
        }
    }
}
